field: 3406380f-3fa1-48ed-a16b-d07bb9e59936
fieldLayouts:
  2db60b5f-cccd-4bb8-8466-87f11d02b42b:
    tabs:
      -
        elements:
          -
            fieldUid: 9ca59183-041b-4408-95e9-eaf9522e4f6a
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 578e36a4-30a0-40a5-a1d6-8a1ae0d87c4a
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
        name: Content
        sortOrder: 1
fields:
  578e36a4-30a0-40a5-a1d6-8a1ae0d87c4a:
    contentColumnType: string
    fieldGroup: null
    handle: titleCaption
    instructions: ''
    name: 'Title + Caption'
    searchable: false
    settings:
      hideLabel: ''
      notes: '<p>The title and caption of the video are edited by double clicking on the video asset to the left, and filling in the `Title` and `Caption` fields.</p>'
      output: richText
      style: ''
    translationKeyFormat: null
    translationMethod: none
    type: barrelstrength\sproutfields\fields\Notes
  9ca59183-041b-4408-95e9-eaf9522e4f6a:
    contentColumnType: string
    fieldGroup: null
    handle: video
    instructions: 'Add a vimeo video by copying the url of the video and pasting into the embed field after clicking on "embed" when in the asset dialog.'
    name: Video
    searchable: false
    settings:
      allowSelfRelations: false
      allowedKinds:
        - json
      defaultUploadLocationSource: 'volume:2607b73d-492a-4009-bac0-59c95f16694a'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      restrictFiles: '1'
      selectionLabel: 'Choose a video'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:2607b73d-492a-4009-bac0-59c95f16694a'
      singleUploadLocationSubpath: '{owner.section}/{owner.slug}'
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: true
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: video
name: Video
sortOrder: 2
