contentColumnType: string
fieldGroup: 404a9b6a-833f-4ea6-9914-e057f51a2b80
handle: philanthropyImage
instructions: ''
name: 'Philanthropy Image'
searchable: true
settings:
  allowSelfRelations: false
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:2607b73d-492a-4009-bac0-59c95f16694a'
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  restrictFiles: '1'
  selectionLabel: 'Choose an image'
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:2607b73d-492a-4009-bac0-59c95f16694a'
  singleUploadLocationSubpath: '{owner.slug}'
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: true
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
