contentColumnType: text
fieldGroup: 404a9b6a-833f-4ea6-9914-e057f51a2b80
handle: philanthropyParagraph
instructions: ''
name: 'Philanthropy Paragraph'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
