contentColumnType: string
fieldGroup: 1ef20c73-d4c2-4889-bc87-e239a901397d
handle: propertyBannerImage
instructions: 'Image displayed at the top of the property page.'
name: 'Property Banner Image'
searchable: false
settings:
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:2607b73d-492a-4009-bac0-59c95f16694a'
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  restrictFiles: '1'
  selectionLabel: 'Choose an image'
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:2607b73d-492a-4009-bac0-59c95f16694a'
  singleUploadLocationSubpath: '{owner.section}/{owner.slug}'
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: true
  validateRelatedElements: ''
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
