contentColumnType: string
fieldGroup: 1ef20c73-d4c2-4889-bc87-e239a901397d
handle: propertyInfo
instructions: 'Informational column displayed at the top of the page.'
name: 'Property Info'
searchable: true
settings:
  contentTable: '{{%matrixcontent_propertyinfo}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
