contentColumnType: string
fieldGroup: decd43eb-d754-4e13-a427-09093c2d8a84
handle: seoImage
instructions: ''
name: 'SEO Image'
searchable: false
settings:
  allowedKinds: null
  defaultUploadLocationSource: 'volume:2607b73d-492a-4009-bac0-59c95f16694a'
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  restrictFiles: ''
  selectionLabel: 'Choose an image'
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:2607b73d-492a-4009-bac0-59c95f16694a'
  singleUploadLocationSubpath: '{owner.slug}'
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: true
  validateRelatedElements: ''
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
