enableVersioning: true
handle: approach
name: Approach
propagationMethod: all
siteSettings:
  2fa33456-77aa-4780-adc6-1103fb992339:
    enabledByDefault: true
    hasUrls: true
    template: approach/index
    uriFormat: approach
type: single
